import { StyledList, Item } from "./styled";

const List = () => (
    <StyledList>
        <Item>
            lalalal
        </Item>
        <Item>
            nininin
        </Item>
        <Item>
            lalalal
        </Item>
        <Item>
            nininin
        </Item>
        <Item>
            lalalal
        </Item>
        <Item>
            nininin
        </Item>
        <Item>
            lalalal
        </Item>
        <Item>
            nininin
        </Item>
        <Item>
            lalalal
        </Item>
        <Item>
            lalalal
        </Item>
        <Item>
            nininin
        </Item>
        <Item>
            lalalal
        </Item>
        <Item>
            lalalal
        </Item>
        <Item>
            nininin
        </Item>
        <Item>
            lalalal
        </Item>
        <Item>
            lalalal
        </Item>
        <Item>
            lalalal
        </Item>
        <Item>
            nininin
        </Item>
        <Item>
            lalalal
        </Item>
    </StyledList>
);

export default List;